name: Build Windows App

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Compilar para .exe
        run: npm run build

      - name: Salvar o arquivo EXE gerado
        uses: actions/upload-artifact@v4
        with:
          name: FunkinSheetStudio-Windows
          path: dist/FunkinSheetStudio-win32-x64/
          
